[package]
name = "Mars_Lander"
version = "0.1.0"
edition = "2024"

[features]
default = ["visualize"]
visualize = ["dep:svg"]

[dependencies]
rand = "0.9"
rayon = "1"
svg = { version = "0.18", optional = true }
